"""unique game fix

Revision ID: b0445df9e787
Revises: 9d0be194d280
Create Date: 2018-12-08 17:19:20.109493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0445df9e787'
down_revision = '9d0be194d280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_name', table_name='game')
    op.create_index(op.f('ix_game_name'), 'game', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_name'), table_name='game')
    op.create_index('ix_game_name', 'game', ['name'], unique=1)
    # ### end Alembic commands ###
